### ISSUE TITLE
Tile tinting

### ISSUE THREAD

**Issue by jleahey** [jleahey/Minicraft#11]
We need to be able to tint tiles for lighting, but our very simplistic java.awt.image, which is hardware accelerated, has no way to do this natively. We could render out different versions of all oft the images at load time, but there are better ways to do this which might carry over something to an Android implementation.

Current approach: Switch to OpenGL using jogl.
http://jogamp.org/jogl/www/

**Comment by perimosocordiae** [comment]
Most of the lighting seems to work right, but there are weirdnesses for (some) blocks diagonally-adjacent to the sky:
![Screen Shot 2012-12-24 at 1 21 10 PM](https://f.cloud.github.com/assets/82855/30063/a4423d52-4e07-11e2-8ea4-4fd234d58386.png)

**Comment by jleahey** [comment]
This is because of the visibility matrix generated by the the world generator. This used to be a feature and it made the ground look nicer, but it's not worth it to have light travel diagonally. Soon visibility needs to be completely removed for lighting, and will require some tweaking.

**Comment by perimosocordiae** [comment]
Cool, I'll just leave the lighting to you, then. :grin:

**Comment by perimosocordiae** [comment]
Recent commits look really good! One last (I hope) small bug:
![Screen Shot 2012-12-27 at 8 09 14 PM](https://f.cloud.github.com/assets/82855/33542/41eff3a0-509c-11e2-9534-f0d66d1af562.png)

It's dark outside (just past midnight) but the non-air tiles are still tinted as in midday. This may be as simple as adding a check to `timeOfDay` in the code that gets the sun sources, but I'll leave this to you.

**Comment by jleahey** [comment]
Will do! This will be a simple fix. Also changeTile needs to activate lighting changes as well. Sand falling currently does not update lighting.

**Comment by jleahey** [comment]
Except that there are no torches, the tile tinting and lighting engine work.
