### ISSUE TITLE
Add torches

### ISSUE THREAD

**Issue by jleahey** [jleahey/Minicraft#16]
We need an 8x8 graphic. A torch needs to become a block with a recipe, and the lighting engine will need to keep track of both sun values and torch values so it can be interpolated smoothly at night.

**Comment by perimosocordiae** [comment]
Also, we may want torches to be placed arbitrarily when underground (to simulate them being placed on a wall). That may be too complicated, though.

We definitely need to make sure that entities can pass through torches (like we can walk through logs).

**Comment by jleahey** [comment]
Indeed. There are a handful of checks for 'a' air that will need to be updated to neatly include all non blocking blocks. Wood should probably have its own maxdx/dy and not just be passable, it uses water dx/dy iirc. I suppose we need a better blocks issue.

**Comment by perimosocordiae** [comment]
Yep, checking for special behavior based on single-character block 'names' makes me cry. evertim.

**Comment by jleahey** [comment]
Evertim. That's definitely an artifact from the one week compo sprint. Now to do the Right Thing (tm).
