### ISSUE TITLE
Graphical glitch with horizontal + vertical black lines

### ISSUE THREAD

**Issue by perimosocordiae** [jleahey/Minicraft#19]
Start a game, look for something like this:
![Screen Shot 2012-12-30 at 11 43 47 AM](https://f.cloud.github.com/assets/82855/36009/0a6b0372-52b1-11e2-87a2-b848e50e69f9.png)

or this

![Screen Shot 2012-12-30 at 11 44 11 AM](https://f.cloud.github.com/assets/82855/36010/0c6b9f24-52b1-11e2-8d4a-6ab239160d46.png)

Only occurs at certain times of day.

**Comment by jleahey** [comment]
Well documented. It's strange that it only happens at certain times of day, perhaps those are the times it's noticeable. It could have something to do with (float) --> (int) pixel conversions in world.draw(...).

**Comment by perimosocordiae** [comment]
Where is this documented, for my future reference?

**Comment by jleahey** [comment]
I was saying you documented the bug well... Minicraft is woefully lacking in documentation mostly due to the way in which it was conceived.

Perhaps it wouldn't be a bad idea to document the genearl flow of the game for things like this...

**Comment by jleahey** [comment]
A quick check shows that casting is the issue

Changing:

```
        for (int i = 0; i < width; i++) {
            for (int j = 0; j < height; j++) {
                int posX = (int) ((i - cameraX) * tileSize);
                int posY = (int) ((j - cameraY) * tileSize);
```

To:

```
        int cameraPosX = (int) (cameraX * tileSize);
        int cameraPosY = (int) (cameraY * tileSize);
        for (int i = 0; i < width; i++) {
            for (int j = 0; j < height; j++) {
                int posX = i * tileSize - cameraPosX;
                int posY = j * tileSize - cameraPosY;
```

Pushes the gapped tiles together, but also causes many other problems, because everything it being drawn using the one transition function from StockMethods.computeDrawLocationInPlace(...) so other things end up being "off by a pixel". This will require further review.

**Comment by jleahey** [comment]
I switched drawing to all floats and stumbled across this, kind of a cool style!:
![Screen Shot 2012-12-31 at 5 46 40 PM](https://f.cloud.github.com/assets/1250914/37020/284abf86-539c-11e2-9d98-d85f07d3313c.png)

**Comment by perimosocordiae** [comment]
Heh, nice! Maybe using doubles would fix it?

**Comment by jleahey** [comment]
Draw calls now simply have a round in them instead of an effective floor by the (int) call. This might slow things down a bit since it happens so often but for now it fixes this issue.
